### ISSUE TITLE
Build docs locally and on readthedocs

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/ai4s2s#15]
Looks like sphinx has already been set up for this repo, and there is a GitHub action to automatically build. However, there are no instructions on how to build the documentation locally, and there doesn't seem to be a readthedocs integration configured for this repo. 

Would be nice to set this up quickly, as there's already some documentation being generated from #12 (and doctests being run, cool stuff!)

**Comment by Peter9192** [comment]
On the README there's a header "documentation" which says: 
> Include a link to your project's full documentation here.

**Comment by Peter9192** [comment]
Instructions for setting up readthedocs:

- Go to https://readthedocs.org
- log in with github
- import a project
- find this repo in the list
- ...

**Comment by Peter9192** [comment]
the command for building docs locally is: `python setup.py build_sphinx`

**Comment by geek-yang** [comment]
The sphinx doc is now integrated with the readthedoc server. The way to set it up is given [here](https://docs.readthedocs.io/en/stable/tutorial/).

**Comment by Peter9192** [comment]
Nice! If we can add some instructions on building the docs locally to the CONTRIBUTING.md guidelines then this issue can be closed.

**Comment by geek-yang** [comment]
> Nice! If we can add some instructions on building the docs locally to the CONTRIBUTING.md guidelines then this issue can be closed.

It has already been mentioned in [README.dev.md](https://github.com/AI4S2S/ai4s2s/blob/developer_docs/docs/README.dev.md) (see the section "Generating the API docs"). But the docs are still a bit chaotic. I think later on we need to restructure it somehow, to make it more organized.

**Comment by Peter9192** [comment]
Okay, then this can be closed :-)
