### ISSUE TITLE
Support `xarray.DataArray` in `resample` function

### ISSUE THREAD

**Issue by geek-yang** [AI4S2S/ai4s2s#17]
As a user, I want to use `resample` function in `s2s.time` module to upscale my `xarray` type data.

**Comment by BSchilperoort** [comment]
I have started on implementing xarray data (both `DataArray` as well `Dataset`) for the `resample` method. However currently the resampled data does not have the lag or anchor year as actual coordinates.

To fully implement xarray objects the following steps have to still be done;

- Reshape the output `Dataset` to have the `lag` and `anchor_year` variables as dimensions/coordinates instead.
- Ensure that the original coordinates of the input data are preserved (e.g. latitude, longitude) to the output `Dataset` without modification..

**Comment by BSchilperoort** [comment]
Implemented in #28
