### ISSUE TITLE
New name for column 'lag' in function map_to_data in time.py

### ISSUE THREAD

**Issue by jannesvaningen** [AI4S2S/ai4s2s#24]
We need a new name for the column name 'lag' in the function map_to_data. https://github.com/AI4S2S/ai4s2s/blob/fa0ad6508b7c1f9e294adfde527c786e7a8f7b8c/s2s/time.py#L176
The name lag does not quite cut it, because it does not acknowledge that the first period after the next target period is also lag 1,2,3 etc.
Current suggestions:
- interval_i
- count
- intval
- i
- bin

**Comment by BSchilperoort** [comment]
Fixed by #28
