### ISSUE TITLE
Order of execution regarding `map_to_data` and `discard` methods

### ISSUE THREAD

**Issue by geek-yang** [AI4S2S/ai4s2s#27]
In our current design, when calling `map_to_data` we must know the `max_lag` (and call the `discard` function to trim the `AdventCalendar`) to enforce that the input will be entirely covered, like what is shown in the figure below.

![1](https://user-images.githubusercontent.com/25911757/174078055-ad9f0607-5e6e-4fa1-9b7d-5898cc6accec.png)

However, when calling the `discard` function, the user needs to know how many time lags does he/she have, by looking the `AdventCalendar`. This results in a circular dependency.

We need to define a workflow for the user to solve this problem.

**Comment by geek-yang** [comment]
For what I could think about, for instance, the user can instantiate the `AdventCalendar`. Pick up a year/years to generate the table view of calendar. Check the calendar to see how many lags are there and determine how many lags do they want to keep. Then call the `discard` with preferred `max_lag` to trim the calendar. And finally map it to their data.

**Comment by Peter9192** [comment]
A few suggestions:

- Forget about discard
- Initial max lag should be set in the init function. It is already calculated (365 / freq), just not stored yet. Store as self._max_lag
- map-to-data then no longer depends on whether discard or set_max_lag or so has been called.
- Later, we could add a getter and setter for max_lag (and perhaps also min_lag?)

**Comment by geek-yang** [comment]
Thanks for your comment @Peter9192 . Given these suggestions, now it is clear for `map_to_data` function, and the way we will implement `self._max_lag`. This issue can be closed when the PR #22 is merged.
