### ISSUE TITLE
Implementing the TimeIndex class - the constructor method

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/ai4s2s#8]
In #7 we drafted a preliminary interface for the main time-index object. Now, we want to start implementing it, starting with the constructor (the `__init__` method). 

Also see the discussion in https://github.com/AI4S2S/proto/issues/3

**Comment by Peter9192** [comment]
The reference implementation creates two dataframes, but they are based on the target variable input array:
https://github.com/AI4S2S/proto/blob/0dd397f6101573544f10a55a4205e037e69acdfe/RGCPD/class_RGCPD.py#L302

Instead, I'd prefer to just create a new array independently from any input data.

**Comment by geek-yang** [comment]
> Instead, I'd prefer to just create a new array independently from any input data.

I think this is a good choice. We manipulate time index and train/test labels in this class and save the output as an independent data (e.g. dataframe). We can bring it to the preprocessing module when the actual operations take place.
